name: Add Milestone
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  merge-job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: andrefcdias/add-to-milestone@v1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          use-pattern: true
          milestone: "*.*.0"
