name: Add Milestone
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  build:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@v1.1.1
