# This is a basic workflow to help you get started with Actions

name: Pull Request Checklist

# Controls when the workflow will run
on: pull_request

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Contextual QA Checklists
        # You may pin to the exact commit or the version.
        # uses: wyozi/contextual-qa-checklist-action@27696c9016d0f9759baaccd2cf5f3002c38d3801
        uses: wyozi/contextual-qa-checklist-action@1.0
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          input-file: app/CHECKLIST.yml
